#! /bin/sh

rsync -avL --timeout 10 --delete --exclude '*.inc*' --exclude '*.lib*' --exclude '*.build*' --exclude '*.orig' --exclude 'deploy*' . alex@preview.condensation.io:/srv/data/preview.condensation.io/http
